from enum import Enum


class FactVerificationStatus(str, Enum):
    CONFIRMED = "CONFIRMED"
    PROPOSED = "PROPOSED"
    UNKNOWN = "UNKNOWN"

class ProductFactType(str, Enum):
    DESCRIPTION = "DESCRIPTION"
    FEATURE = "FEATURE"
    INGREDIENT = "INGREDIENT"
    SPECIFICATION = "SPECIFICATION"
    USAGE = "USAGE"
    AVAILABILITY = "AVAILABILITY"

class BrandRuleType(str, Enum):
    REQUIRED = "REQUIRED"
    FORBIDDEN = "FORBIDDEN"
    PREFERRED = "PREFERRED"
    DISCOURAGED = "DISCOURAGED"