"""add asset requirements

Revision ID: 08b64f509bc0
Revises: 7d4b4ebb6796
Create Date: 2026-09-13 17:56:14.777485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08b64f509bc0'
down_revision: Union[str, Sequence[str], None] = '7d4b4ebb6796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_requirements',
    sa.Column('storyboard_scene_id', sa.Uuid(), nullable=False),
    sa.Column('requirement_key', sa.String(length=64), nullable=False),
    sa.Column('asset_kind', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_type', sa.Enum('USER_PROVIDED', 'AI_SUGGESTED', 'IMPORTED_DATA', 'SYSTEM_GENERATED', name='sourcetype', native_enum=False, length=32), nullable=False),
    sa.ForeignKeyConstraint(['storyboard_scene_id'], ['storyboard_scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storyboard_scene_id', 'requirement_key', name='uq_asset_requirements_scene_key')
    )
    op.create_index(op.f('ix_asset_requirements_storyboard_scene_id'), 'asset_requirements', ['storyboard_scene_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_requirements_storyboard_scene_id'), table_name='asset_requirements')
    op.drop_table('asset_requirements')
    # ### end Alembic commands ###
