"""add performance findings

Revision ID: 171ee4b06fa3
Revises: 2decd9db78e1
Create Date: 2026-09-13 20:51:57.192863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '171ee4b06fa3'
down_revision: Union[str, Sequence[str], None] = '2decd9db78e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_findings',
    sa.Column('publication_id', sa.Uuid(), nullable=False),
    sa.Column('finding_kind', sa.String(length=64), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_type', sa.Enum('USER_PROVIDED', 'AI_SUGGESTED', 'IMPORTED_DATA', 'SYSTEM_GENERATED', name='sourcetype', native_enum=False, length=32), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_findings_publication_id'), 'performance_findings', ['publication_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_performance_findings_publication_id'), table_name='performance_findings')
    op.drop_table('performance_findings')
    # ### end Alembic commands ###
