"""add approvals

Revision ID: 204dd0b93507
Revises: 8d1267b104f1
Create Date: 2026-09-13 18:40:38.365764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '204dd0b93507'
down_revision: Union[str, Sequence[str], None] = '8d1267b104f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('final_asset_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'CHANGES_REQUESTED', 'REJECTED', 'CANCELLED', name='approvalstatus', native_enum=False, length=32), server_default='PENDING', nullable=False),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('request_note', sa.Text(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['final_asset_id'], ['final_assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_final_asset_id'), 'approvals', ['final_asset_id'], unique=False)
    op.create_index(op.f('ix_approvals_requested_by_user_id'), 'approvals', ['requested_by_user_id'], unique=False)
    op.create_index(op.f('ix_approvals_reviewed_by_user_id'), 'approvals', ['reviewed_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approvals_reviewed_by_user_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_requested_by_user_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_final_asset_id'), table_name='approvals')
    op.drop_table('approvals')
    # ### end Alembic commands ###
