"""add performance metrics

Revision ID: 2decd9db78e1
Revises: 672977db4fe6
Create Date: 2026-09-13 20:29:28.451212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2decd9db78e1'
down_revision: Union[str, Sequence[str], None] = '672977db4fe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_metrics',
    sa.Column('performance_record_id', sa.Uuid(), nullable=False),
    sa.Column('metric_key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['performance_record_id'], ['performance_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('performance_record_id', 'metric_key', name='uq_performance_metrics_record_key')
    )
    op.create_index(op.f('ix_performance_metrics_performance_record_id'), 'performance_metrics', ['performance_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_performance_metrics_performance_record_id'), table_name='performance_metrics')
    op.drop_table('performance_metrics')
    # ### end Alembic commands ###
