"""add brand facts

Revision ID: 44a1ef7ee657
Revises: 966ccbdf5883
Create Date: 2026-09-13 00:33:59.581118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44a1ef7ee657'
down_revision: Union[str, Sequence[str], None] = '966ccbdf5883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_facts',
    sa.Column('brand_profile_id', sa.Uuid(), nullable=False),
    sa.Column('fact_type', sa.Enum('INDUSTRY', 'BUSINESS_MODEL', 'LOCATION', 'OPERATING_AREA', 'CONTACT', name='brandfacttype', native_enum=False, length=32), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('verification_status', sa.Enum('CONFIRMED', 'PROPOSED', 'UNKNOWN', name='factverificationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_type', sa.Enum('USER_PROVIDED', 'AI_SUGGESTED', 'IMPORTED_DATA', 'SYSTEM_GENERATED', name='sourcetype', native_enum=False, length=32), nullable=False),
    sa.ForeignKeyConstraint(['brand_profile_id'], ['brand_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_facts_brand_profile_id'), 'brand_facts', ['brand_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brand_facts_brand_profile_id'), table_name='brand_facts')
    op.drop_table('brand_facts')
    # ### end Alembic commands ###
