"""add production assets

Revision ID: 4779de1d4c0e
Revises: 08b64f509bc0
Create Date: 2026-09-13 18:03:50.156175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4779de1d4c0e'
down_revision: Union[str, Sequence[str], None] = '08b64f509bc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_assets',
    sa.Column('production_run_id', sa.Uuid(), nullable=False),
    sa.Column('asset_requirement_id', sa.Uuid(), nullable=False),
    sa.Column('asset_kind', sa.String(length=64), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('provider_key', sa.String(length=128), nullable=True),
    sa.Column('provider_asset_id', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_requirement_id'], ['asset_requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['production_run_id'], ['production_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_assets_asset_requirement_id'), 'production_assets', ['asset_requirement_id'], unique=False)
    op.create_index(op.f('ix_production_assets_production_run_id'), 'production_assets', ['production_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_assets_production_run_id'), table_name='production_assets')
    op.drop_index(op.f('ix_production_assets_asset_requirement_id'), table_name='production_assets')
    op.drop_table('production_assets')
    # ### end Alembic commands ###
