"""add creative decisions

Revision ID: 4b17fbfcc5d2
Revises: b154480f1ed3
Create Date: 2026-09-13 15:37:10.910112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b17fbfcc5d2'
down_revision: Union[str, Sequence[str], None] = 'b154480f1ed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creative_decisions',
    sa.Column('creative_brief_id', sa.Uuid(), nullable=False),
    sa.Column('decision_kind', sa.String(length=64), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_type', sa.Enum('USER_PROVIDED', 'AI_SUGGESTED', 'IMPORTED_DATA', 'SYSTEM_GENERATED', name='sourcetype', native_enum=False, length=32), nullable=False),
    sa.ForeignKeyConstraint(['creative_brief_id'], ['creative_briefs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creative_decisions_creative_brief_id'), 'creative_decisions', ['creative_brief_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_creative_decisions_creative_brief_id'), table_name='creative_decisions')
    op.drop_table('creative_decisions')
    # ### end Alembic commands ###
