"""add video brief instructions

Revision ID: 4c221d275968
Revises: 716ab169e447
Create Date: 2026-09-13 16:27:05.166056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c221d275968'
down_revision: Union[str, Sequence[str], None] = '716ab169e447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_brief_instructions',
    sa.Column('video_brief_id', sa.Uuid(), nullable=False),
    sa.Column('instruction_kind', sa.String(length=64), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_type', sa.Enum('USER_PROVIDED', 'AI_SUGGESTED', 'IMPORTED_DATA', 'SYSTEM_GENERATED', name='sourcetype', native_enum=False, length=32), nullable=False),
    sa.ForeignKeyConstraint(['video_brief_id'], ['video_briefs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_brief_instructions_video_brief_id'), 'video_brief_instructions', ['video_brief_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_brief_instructions_video_brief_id'), table_name='video_brief_instructions')
    op.drop_table('video_brief_instructions')
    # ### end Alembic commands ###
