"""add storyboard scenes

Revision ID: 4c74e7e82da5
Revises: 3b18e91e59db
Create Date: 2026-09-13 16:48:16.060778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c74e7e82da5'
down_revision: Union[str, Sequence[str], None] = '3b18e91e59db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storyboard_scenes',
    sa.Column('storyboard_id', sa.Uuid(), nullable=False),
    sa.Column('scene_key', sa.String(length=64), nullable=False),
    sa.Column('sequence_index', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('voiceover_text', sa.Text(), nullable=True),
    sa.Column('visual_direction', sa.Text(), nullable=True),
    sa.Column('on_screen_text', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_type', sa.Enum('USER_PROVIDED', 'AI_SUGGESTED', 'IMPORTED_DATA', 'SYSTEM_GENERATED', name='sourcetype', native_enum=False, length=32), nullable=False),
    sa.ForeignKeyConstraint(['storyboard_id'], ['storyboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storyboard_id', 'scene_key', name='uq_storyboard_scenes_storyboard_key'),
    sa.UniqueConstraint('storyboard_id', 'sequence_index', name='uq_storyboard_scenes_storyboard_sequence')
    )
    op.create_index(op.f('ix_storyboard_scenes_storyboard_id'), 'storyboard_scenes', ['storyboard_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_storyboard_scenes_storyboard_id'), table_name='storyboard_scenes')
    op.drop_table('storyboard_scenes')
    # ### end Alembic commands ###
