"""add publications

Revision ID: 4c889590954d
Revises: e15da2041d89
Create Date: 2026-09-13 19:20:52.072731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c889590954d'
down_revision: Union[str, Sequence[str], None] = 'e15da2041d89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publications',
    sa.Column('final_asset_id', sa.Uuid(), nullable=False),
    sa.Column('approval_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PUBLISHING', 'PUBLISHED', 'FAILED', 'CANCELLED', name='publicationstatus', native_enum=False, length=32), server_default='PENDING', nullable=False),
    sa.Column('provider_key', sa.String(length=128), nullable=True),
    sa.Column('external_publication_id', sa.String(length=255), nullable=True),
    sa.Column('published_url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['final_asset_id'], ['final_assets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publications_approval_id'), 'publications', ['approval_id'], unique=False)
    op.create_index(op.f('ix_publications_final_asset_id'), 'publications', ['final_asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publications_final_asset_id'), table_name='publications')
    op.drop_index(op.f('ix_publications_approval_id'), table_name='publications')
    op.drop_table('publications')
    # ### end Alembic commands ###
