"""add strategy decision requirement links

Revision ID: 4e1c3f7224e2
Revises: 5b334ca7fbc2
Create Date: 2026-09-13 14:23:03.610915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e1c3f7224e2'
down_revision: Union[str, Sequence[str], None] = '5b334ca7fbc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_decision_requirements',
    sa.Column('strategy_decision_id', sa.Uuid(), nullable=False),
    sa.Column('marketing_requirement_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['marketing_requirement_id'], ['marketing_requirements.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['strategy_decision_id'], ['strategy_decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_decision_id', 'marketing_requirement_id', name='uq_strategy_decision_requirement_pair')
    )
    op.create_index(op.f('ix_strategy_decision_requirements_marketing_requirement_id'), 'strategy_decision_requirements', ['marketing_requirement_id'], unique=False)
    op.create_index(op.f('ix_strategy_decision_requirements_strategy_decision_id'), 'strategy_decision_requirements', ['strategy_decision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_decision_requirements_strategy_decision_id'), table_name='strategy_decision_requirements')
    op.drop_index(op.f('ix_strategy_decision_requirements_marketing_requirement_id'), table_name='strategy_decision_requirements')
    op.drop_table('strategy_decision_requirements')
    # ### end Alembic commands ###
