"""add strategy decision finding links

Revision ID: 5b334ca7fbc2
Revises: 8c4d374ca70b
Create Date: 2026-09-13 14:03:54.375953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b334ca7fbc2'
down_revision: Union[str, Sequence[str], None] = '8c4d374ca70b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_decision_findings',
    sa.Column('strategy_decision_id', sa.Uuid(), nullable=False),
    sa.Column('research_finding_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['research_finding_id'], ['research_findings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['strategy_decision_id'], ['strategy_decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_decision_id', 'research_finding_id', name='uq_strategy_decision_finding_pair')
    )
    op.create_index(op.f('ix_strategy_decision_findings_research_finding_id'), 'strategy_decision_findings', ['research_finding_id'], unique=False)
    op.create_index(op.f('ix_strategy_decision_findings_strategy_decision_id'), 'strategy_decision_findings', ['strategy_decision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_decision_findings_strategy_decision_id'), table_name='strategy_decision_findings')
    op.drop_index(op.f('ix_strategy_decision_findings_research_finding_id'), table_name='strategy_decision_findings')
    op.drop_table('strategy_decision_findings')
    # ### end Alembic commands ###
