"""add brand voice

Revision ID: 5c3ad3c91a1c
Revises: de3acf2df471
Create Date: 2026-09-12 23:59:33.430817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c3ad3c91a1c'
down_revision: Union[str, Sequence[str], None] = 'de3acf2df471'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_voices',
    sa.Column('brand_profile_id', sa.Uuid(), nullable=False),
    sa.Column('primary_language', sa.String(length=32), nullable=False),
    sa.Column('tone', sa.Text(), nullable=True),
    sa.Column('personality', sa.Text(), nullable=True),
    sa.Column('style_guidelines', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_profile_id'], ['brand_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_voices_brand_profile_id'), 'brand_voices', ['brand_profile_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brand_voices_brand_profile_id'), table_name='brand_voices')
    op.drop_table('brand_voices')
    # ### end Alembic commands ###
