"""add research task executions

Revision ID: 5d0ed21db142
Revises: f8984576722c
Create Date: 2026-09-13 08:46:58.102563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d0ed21db142'
down_revision: Union[str, Sequence[str], None] = 'f8984576722c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_task_executions',
    sa.Column('research_run_id', sa.Uuid(), nullable=False),
    sa.Column('research_task_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', name='researchtaskexecutionstatus', native_enum=False, length=32), server_default='PENDING', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['research_task_id'], ['research_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('research_run_id', 'research_task_id', name='uq_research_task_executions_run_task')
    )
    op.create_index(op.f('ix_research_task_executions_research_run_id'), 'research_task_executions', ['research_run_id'], unique=False)
    op.create_index(op.f('ix_research_task_executions_research_task_id'), 'research_task_executions', ['research_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_task_executions_research_task_id'), table_name='research_task_executions')
    op.drop_index(op.f('ix_research_task_executions_research_run_id'), table_name='research_task_executions')
    op.drop_table('research_task_executions')
    # ### end Alembic commands ###
