"""add research finding evidence links

Revision ID: 64d993e3a993
Revises: 34bb7797471a
Create Date: 2026-09-13 09:44:09.188795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64d993e3a993'
down_revision: Union[str, Sequence[str], None] = '34bb7797471a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_finding_evidence',
    sa.Column('research_finding_id', sa.Uuid(), nullable=False),
    sa.Column('research_evidence_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['research_evidence_id'], ['research_evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['research_finding_id'], ['research_findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('research_finding_id', 'research_evidence_id', name='uq_research_finding_evidence_pair')
    )
    op.create_index(op.f('ix_research_finding_evidence_research_evidence_id'), 'research_finding_evidence', ['research_evidence_id'], unique=False)
    op.create_index(op.f('ix_research_finding_evidence_research_finding_id'), 'research_finding_evidence', ['research_finding_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_finding_evidence_research_finding_id'), table_name='research_finding_evidence')
    op.drop_index(op.f('ix_research_finding_evidence_research_evidence_id'), table_name='research_finding_evidence')
    op.drop_table('research_finding_evidence')
    # ### end Alembic commands ###
