"""add performance records

Revision ID: 672977db4fe6
Revises: 4c889590954d
Create Date: 2026-09-13 20:21:08.330894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '672977db4fe6'
down_revision: Union[str, Sequence[str], None] = '4c889590954d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_records',
    sa.Column('publication_id', sa.Uuid(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_key', sa.String(length=128), nullable=True),
    sa.Column('external_record_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_records_publication_id'), 'performance_records', ['publication_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_performance_records_publication_id'), table_name='performance_records')
    op.drop_table('performance_records')
    # ### end Alembic commands ###
