"""add video brief foundation

Revision ID: 716ab169e447
Revises: a05b461c4cfe
Create Date: 2026-09-13 16:13:11.470672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '716ab169e447'
down_revision: Union[str, Sequence[str], None] = 'a05b461c4cfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_briefs',
    sa.Column('creative_variant_id', sa.Uuid(), nullable=False),
    sa.Column('parent_version_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='entitystatus', native_enum=False, length=32), server_default='DRAFT', nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('schema_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_outdated', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['creative_variant_id'], ['creative_variants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_version_id'], ['video_briefs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('creative_variant_id', 'version', name='uq_video_briefs_creative_variant_version')
    )
    op.create_index(op.f('ix_video_briefs_creative_variant_id'), 'video_briefs', ['creative_variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_briefs_creative_variant_id'), table_name='video_briefs')
    op.drop_table('video_briefs')
    # ### end Alembic commands ###
