"""add final assets

Revision ID: 753d07246dd5
Revises: 4779de1d4c0e
Create Date: 2026-09-13 18:16:04.290711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '753d07246dd5'
down_revision: Union[str, Sequence[str], None] = '4779de1d4c0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('final_assets',
    sa.Column('production_run_id', sa.Uuid(), nullable=False),
    sa.Column('output_key', sa.String(length=64), nullable=False),
    sa.Column('asset_kind', sa.String(length=64), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['production_run_id'], ['production_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('production_run_id', 'output_key', name='uq_final_assets_run_output_key')
    )
    op.create_index(op.f('ix_final_assets_production_run_id'), 'final_assets', ['production_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_final_assets_production_run_id'), table_name='final_assets')
    op.drop_table('final_assets')
    # ### end Alembic commands ###
