"""add product facts

Revision ID: 78d30e991be8
Revises: 0f6571fa25eb
Create Date: 2026-09-12 23:15:27.330221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78d30e991be8'
down_revision: Union[str, Sequence[str], None] = '0f6571fa25eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_facts',
    sa.Column('product_truth_id', sa.Uuid(), nullable=False),
    sa.Column('fact_type', sa.Enum('DESCRIPTION', 'FEATURE', 'INGREDIENT', 'SPECIFICATION', 'USAGE', 'AVAILABILITY', name='productfacttype', native_enum=False, length=32), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('verification_status', sa.Enum('CONFIRMED', 'PROPOSED', 'UNKNOWN', name='factverificationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_type', sa.Enum('USER_PROVIDED', 'AI_SUGGESTED', 'IMPORTED_DATA', 'SYSTEM_GENERATED', name='sourcetype', native_enum=False, length=32), nullable=False),
    sa.ForeignKeyConstraint(['product_truth_id'], ['product_truths.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_facts_product_truth_id'), 'product_facts', ['product_truth_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_facts_product_truth_id'), table_name='product_facts')
    op.drop_table('product_facts')
    # ### end Alembic commands ###
