"""add channel plans

Revision ID: 81e85430ef8c
Revises: 11f62f415ab4
Create Date: 2026-09-13 14:58:15.008379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81e85430ef8c'
down_revision: Union[str, Sequence[str], None] = '11f62f415ab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_plans',
    sa.Column('campaign_plan_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_type', sa.Enum('USER_PROVIDED', 'AI_SUGGESTED', 'IMPORTED_DATA', 'SYSTEM_GENERATED', name='sourcetype', native_enum=False, length=32), nullable=False),
    sa.ForeignKeyConstraint(['campaign_plan_id'], ['campaign_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_plan_id', 'channel', name='uq_channel_plans_campaign_plan_channel')
    )
    op.create_index(op.f('ix_channel_plans_campaign_plan_id'), 'channel_plans', ['campaign_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_plans_campaign_plan_id'), table_name='channel_plans')
    op.drop_table('channel_plans')
    # ### end Alembic commands ###
