"""add research evidence

Revision ID: 835ae9406622
Revises: 5d0ed21db142
Create Date: 2026-09-13 09:20:21.272333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '835ae9406622'
down_revision: Union[str, Sequence[str], None] = '5d0ed21db142'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_evidence',
    sa.Column('research_task_execution_id', sa.Uuid(), nullable=False),
    sa.Column('source_kind', sa.String(length=64), nullable=False),
    sa.Column('provider_key', sa.String(length=128), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_uri', sa.Text(), nullable=True),
    sa.Column('source_external_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('content_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['research_task_execution_id'], ['research_task_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('research_task_execution_id', 'content_fingerprint', name='uq_research_evidence_execution_fingerprint')
    )
    op.create_index(op.f('ix_research_evidence_research_task_execution_id'), 'research_evidence', ['research_task_execution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_evidence_research_task_execution_id'), table_name='research_evidence')
    op.drop_table('research_evidence')
    # ### end Alembic commands ###
