"""add final asset inputs

Revision ID: 8d1267b104f1
Revises: 753d07246dd5
Create Date: 2026-09-13 18:24:23.785757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d1267b104f1'
down_revision: Union[str, Sequence[str], None] = '753d07246dd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('final_asset_inputs',
    sa.Column('final_asset_id', sa.Uuid(), nullable=False),
    sa.Column('production_asset_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['final_asset_id'], ['final_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['production_asset_id'], ['production_assets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('final_asset_id', 'production_asset_id', name='uq_final_asset_inputs_pair')
    )
    op.create_index(op.f('ix_final_asset_inputs_final_asset_id'), 'final_asset_inputs', ['final_asset_id'], unique=False)
    op.create_index(op.f('ix_final_asset_inputs_production_asset_id'), 'final_asset_inputs', ['production_asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_final_asset_inputs_production_asset_id'), table_name='final_asset_inputs')
    op.drop_index(op.f('ix_final_asset_inputs_final_asset_id'), table_name='final_asset_inputs')
    op.drop_table('final_asset_inputs')
    # ### end Alembic commands ###
