"""add research plan foundation

Revision ID: 8de69a93cb02
Revises: 94b7a0aee5cb
Create Date: 2026-09-13 08:10:31.578279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8de69a93cb02'
down_revision: Union[str, Sequence[str], None] = '94b7a0aee5cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_plans',
    sa.Column('marketing_brief_id', sa.Uuid(), nullable=False),
    sa.Column('parent_version_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='entitystatus', native_enum=False, length=32), server_default='DRAFT', nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('schema_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_outdated', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['marketing_brief_id'], ['marketing_briefs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_version_id'], ['research_plans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('marketing_brief_id', 'version', name='uq_research_plans_marketing_brief_version')
    )
    op.create_index(op.f('ix_research_plans_marketing_brief_id'), 'research_plans', ['marketing_brief_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_plans_marketing_brief_id'), table_name='research_plans')
    op.drop_table('research_plans')
    # ### end Alembic commands ###
