"""add marketing requirements

Revision ID: 94b7a0aee5cb
Revises: f4204d2fbe96
Create Date: 2026-09-13 07:46:01.818038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94b7a0aee5cb'
down_revision: Union[str, Sequence[str], None] = 'f4204d2fbe96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketing_requirements',
    sa.Column('marketing_brief_id', sa.Uuid(), nullable=False),
    sa.Column('requirement_type', sa.Enum('OBJECTIVE', 'TARGET_AUDIENCE', 'OFFER', 'CHANNEL', 'BUDGET', 'TIMELINE', 'GEOGRAPHY', 'CONSTRAINT', 'KPI', name='marketingrequirementtype', native_enum=False, length=32), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('decision_status', sa.Enum('CONFIRMED', 'PROPOSED', 'UNKNOWN', name='marketingdecisionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_type', sa.Enum('USER_PROVIDED', 'AI_SUGGESTED', 'IMPORTED_DATA', 'SYSTEM_GENERATED', name='sourcetype', native_enum=False, length=32), nullable=False),
    sa.ForeignKeyConstraint(['marketing_brief_id'], ['marketing_briefs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketing_requirements_marketing_brief_id'), 'marketing_requirements', ['marketing_brief_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketing_requirements_marketing_brief_id'), table_name='marketing_requirements')
    op.drop_table('marketing_requirements')
    # ### end Alembic commands ###
