"""add brand rules

Revision ID: 966ccbdf5883
Revises: 5c3ad3c91a1c
Create Date: 2026-09-13 00:12:27.536854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '966ccbdf5883'
down_revision: Union[str, Sequence[str], None] = '5c3ad3c91a1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_rules',
    sa.Column('brand_profile_id', sa.Uuid(), nullable=False),
    sa.Column('rule_type', sa.Enum('REQUIRED', 'FORBIDDEN', 'PREFERRED', 'DISCOURAGED', name='brandruletype', native_enum=False, length=32), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_profile_id'], ['brand_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_rules_brand_profile_id'), 'brand_rules', ['brand_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brand_rules_brand_profile_id'), table_name='brand_rules')
    op.drop_table('brand_rules')
    # ### end Alembic commands ###
