"""add creative variant decision links

Revision ID: a05b461c4cfe
Revises: a8841507122e
Create Date: 2026-09-13 15:50:50.975278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a05b461c4cfe'
down_revision: Union[str, Sequence[str], None] = 'a8841507122e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creative_variant_decisions',
    sa.Column('creative_variant_id', sa.Uuid(), nullable=False),
    sa.Column('creative_decision_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creative_decision_id'], ['creative_decisions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['creative_variant_id'], ['creative_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('creative_variant_id', 'creative_decision_id', name='uq_creative_variant_decision_pair')
    )
    op.create_index(op.f('ix_creative_variant_decisions_creative_decision_id'), 'creative_variant_decisions', ['creative_decision_id'], unique=False)
    op.create_index(op.f('ix_creative_variant_decisions_creative_variant_id'), 'creative_variant_decisions', ['creative_variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_creative_variant_decisions_creative_variant_id'), table_name='creative_variant_decisions')
    op.drop_index(op.f('ix_creative_variant_decisions_creative_decision_id'), table_name='creative_variant_decisions')
    op.drop_table('creative_variant_decisions')
    # ### end Alembic commands ###
