"""add creative variants

Revision ID: a8841507122e
Revises: 4b17fbfcc5d2
Create Date: 2026-09-13 15:43:38.766102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8841507122e'
down_revision: Union[str, Sequence[str], None] = '4b17fbfcc5d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creative_variants',
    sa.Column('creative_brief_id', sa.Uuid(), nullable=False),
    sa.Column('variant_key', sa.String(length=64), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_type', sa.Enum('USER_PROVIDED', 'AI_SUGGESTED', 'IMPORTED_DATA', 'SYSTEM_GENERATED', name='sourcetype', native_enum=False, length=32), nullable=False),
    sa.ForeignKeyConstraint(['creative_brief_id'], ['creative_briefs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('creative_brief_id', 'variant_key', name='uq_creative_variants_brief_key')
    )
    op.create_index(op.f('ix_creative_variants_creative_brief_id'), 'creative_variants', ['creative_brief_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_creative_variants_creative_brief_id'), table_name='creative_variants')
    op.drop_table('creative_variants')
    # ### end Alembic commands ###
