"""add performance finding metrics

Revision ID: ae557131b81c
Revises: 171ee4b06fa3
Create Date: 2026-09-13 20:59:15.748758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae557131b81c'
down_revision: Union[str, Sequence[str], None] = '171ee4b06fa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_finding_metrics',
    sa.Column('performance_finding_id', sa.Uuid(), nullable=False),
    sa.Column('performance_metric_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['performance_finding_id'], ['performance_findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performance_metric_id'], ['performance_metrics.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('performance_finding_id', 'performance_metric_id', name='uq_performance_finding_metrics_pair')
    )
    op.create_index(op.f('ix_performance_finding_metrics_performance_finding_id'), 'performance_finding_metrics', ['performance_finding_id'], unique=False)
    op.create_index(op.f('ix_performance_finding_metrics_performance_metric_id'), 'performance_finding_metrics', ['performance_metric_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_performance_finding_metrics_performance_metric_id'), table_name='performance_finding_metrics')
    op.drop_index(op.f('ix_performance_finding_metrics_performance_finding_id'), table_name='performance_finding_metrics')
    op.drop_table('performance_finding_metrics')
    # ### end Alembic commands ###
