"""add creative brief foundation

Revision ID: b154480f1ed3
Revises: be651bbbccde
Create Date: 2026-09-13 15:27:06.412677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b154480f1ed3'
down_revision: Union[str, Sequence[str], None] = 'be651bbbccde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creative_briefs',
    sa.Column('content_item_id', sa.Uuid(), nullable=False),
    sa.Column('parent_version_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='entitystatus', native_enum=False, length=32), server_default='DRAFT', nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('schema_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_outdated', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_version_id'], ['creative_briefs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_item_id', 'version', name='uq_creative_briefs_content_item_version')
    )
    op.create_index(op.f('ix_creative_briefs_content_item_id'), 'creative_briefs', ['content_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_creative_briefs_content_item_id'), table_name='creative_briefs')
    op.drop_table('creative_briefs')
    # ### end Alembic commands ###
