"""add content item scheduling

Revision ID: be651bbbccde
Revises: b97736a14401
Create Date: 2026-09-13 15:10:59.143709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be651bbbccde'
down_revision: Union[str, Sequence[str], None] = 'b97736a14401'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_items', sa.Column('planned_publish_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_items', 'planned_publish_at')
    # ### end Alembic commands ###
