"""add research tasks

Revision ID: d5af6debd0e4
Revises: 8de69a93cb02
Create Date: 2026-09-13 08:23:35.903879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5af6debd0e4'
down_revision: Union[str, Sequence[str], None] = '8de69a93cb02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_tasks',
    sa.Column('research_plan_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_type', sa.Enum('USER_PROVIDED', 'AI_SUGGESTED', 'IMPORTED_DATA', 'SYSTEM_GENERATED', name='sourcetype', native_enum=False, length=32), nullable=False),
    sa.CheckConstraint(
    'position >= 1',
    name='ck_research_tasks_position_positive'
    ),
    sa.ForeignKeyConstraint(['research_plan_id'], ['research_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('research_plan_id', 'position', name='uq_research_tasks_plan_position')
    )
    op.create_index(op.f('ix_research_tasks_research_plan_id'), 'research_tasks', ['research_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_tasks_research_plan_id'), table_name='research_tasks')
    op.drop_table('research_tasks')
    # ### end Alembic commands ###
