"""add product claim evidence

Revision ID: de3acf2df471
Revises: 55956e6d76eb
Create Date: 2026-09-12 23:51:31.012290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de3acf2df471'
down_revision: Union[str, Sequence[str], None] = '55956e6d76eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_claim_evidence',
    sa.Column('product_claim_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reference_uri', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.Enum('CONFIRMED', 'PROPOSED', 'UNKNOWN', name='factverificationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_type', sa.Enum('USER_PROVIDED', 'AI_SUGGESTED', 'IMPORTED_DATA', 'SYSTEM_GENERATED', name='sourcetype', native_enum=False, length=32), nullable=False),
    sa.ForeignKeyConstraint(['product_claim_id'], ['product_claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_claim_evidence_product_claim_id'), 'product_claim_evidence', ['product_claim_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_claim_evidence_product_claim_id'), table_name='product_claim_evidence')
    op.drop_table('product_claim_evidence')
    # ### end Alembic commands ###
