"""add project lifecycle status

Revision ID: fbd980f3c5d1
Revises: a067da4014f1
Create Date: 2026-09-12 20:52:15.396952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbd980f3c5d1'
down_revision: Union[str, Sequence[str], None] = 'a067da4014f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='entitystatus', native_enum=False, length=32), server_default='DRAFT', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'status')
    # ### end Alembic commands ###
